"""
src/export_utils.py — Export chat history to TXT, PDF, or DOCX.
"""

import io
import datetime
from typing import Optional


APP_TITLE = "Indispensable Values Q&A"
WATERMARK = "Generated by Indispensable Values Q&A — A Vedantic Study Companion"


def _format_message(msg: dict, idx: int) -> str:
    """Format a single chat message as plain text."""
    role = "🙋 You" if msg["role"] == "user" else "🪷 Swamiji's Teachings"
    content = msg.get("content", "")
    return f"{role}:\n{content}\n"


# ── TXT Export ─────────────────────────────────────────────────────────────────
def export_to_txt(messages: list[dict], title: str = APP_TITLE) -> bytes:
    """Export chat history as a plain text file."""
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        "=" * 60,
        f"  {title}",
        f"  Exported: {now}",
        "=" * 60,
        "",
    ]
    for i, msg in enumerate(messages):
        lines.append(_format_message(msg, i))
        lines.append("-" * 40)
        lines.append("")

    lines.append(WATERMARK)
    return "\n".join(lines).encode("utf-8")


# ── PDF Export ─────────────────────────────────────────────────────────────────
def export_to_pdf(messages: list[dict], title: str = APP_TITLE) -> Optional[bytes]:
    """
    Export chat history as a PDF.
    Requires reportlab. Returns None if unavailable.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, HRFlowable
        )
        from reportlab.lib.enums import TA_LEFT, TA_CENTER
    except ImportError:
        return None

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2.5 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    GOLD = colors.HexColor("#d4af57")
    DARK = colors.HexColor("#1a0a2e")

    title_style = ParagraphStyle(
        "TitleStyle",
        parent=styles["Title"],
        fontSize=18,
        textColor=DARK,
        spaceAfter=6,
        fontName="Times-Bold",
    )
    subtitle_style = ParagraphStyle(
        "SubStyle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.grey,
        spaceAfter=16,
        alignment=TA_CENTER,
    )
    user_label_style = ParagraphStyle(
        "UserLabel",
        parent=styles["Normal"],
        fontSize=9,
        textColor=GOLD,
        fontName="Helvetica-Bold",
        spaceBefore=8,
        spaceAfter=2,
    )
    bot_label_style = ParagraphStyle(
        "BotLabel",
        parent=styles["Normal"],
        fontSize=9,
        textColor=DARK,
        fontName="Helvetica-Bold",
        spaceBefore=8,
        spaceAfter=2,
    )
    body_style = ParagraphStyle(
        "BodyStyle",
        parent=styles["Normal"],
        fontSize=10,
        leading=14,
        spaceAfter=4,
    )

    story = []
    now = datetime.datetime.now().strftime("%d %B %Y, %H:%M")

    story.append(Paragraph(title, title_style))
    story.append(Paragraph(f"A Vedantic Study Companion — {now}", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1, color=GOLD, spaceAfter=12))

    for msg in messages:
        role = msg.get("role", "user")
        content = msg.get("content", "").replace("\n", "<br/>")
        content = content.replace("**", "")  # strip markdown bold for PDF

        if role == "user":
            story.append(Paragraph("You asked:", user_label_style))
        else:
            story.append(Paragraph("Swamiji's Teachings:", bot_label_style))

        story.append(Paragraph(content, body_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.lightgrey, spaceAfter=4))

    story.append(Spacer(1, 12))
    story.append(Paragraph(WATERMARK, subtitle_style))

    doc.build(story)
    return buffer.getvalue()


# ── DOCX Export ────────────────────────────────────────────────────────────────
def export_to_docx(messages: list[dict], title: str = APP_TITLE) -> Optional[bytes]:
    """
    Export chat history as a DOCX file.
    Requires python-docx. Returns None if unavailable.
    """
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor, Inches
        from docx.enum.text import WD_ALIGN_PARAGRAPH
    except ImportError:
        return None

    doc = Document()

    # Title
    title_para = doc.add_heading(title, level=1)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    now = datetime.datetime.now().strftime("%d %B %Y, %H:%M")
    sub = doc.add_paragraph(f"Exported: {now}")
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub.runs[0].font.color.rgb = RGBColor(0x88, 0x88, 0x88)
    sub.runs[0].font.size = Pt(9)

    doc.add_paragraph("─" * 60)

    for msg in messages:
        role = msg.get("role", "user")
        content = msg.get("content", "")

        if role == "user":
            label = doc.add_paragraph()
            run = label.add_run("You asked:")
            run.bold = True
            run.font.color.rgb = RGBColor(0xD4, 0xAF, 0x57)
            run.font.size = Pt(10)
        else:
            label = doc.add_paragraph()
            run = label.add_run("Swamiji's Teachings (via Knowledge Base):")
            run.bold = True
            run.font.size = Pt(10)

        # Add content paragraph by paragraph
        for line in content.split("\n"):
            if line.strip():
                p = doc.add_paragraph(line.replace("**", ""))
                p.runs[0].font.size = Pt(10) if p.runs else None

        doc.add_paragraph("─" * 40)

    doc.add_paragraph(WATERMARK).runs[0].font.color.rgb = RGBColor(0x99, 0x99, 0x99)

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()
